data:
    name: 'angiogram' #hpatches
    data_dir: './data/angiogram/images' #./data/hpatches
    export_dir: './data/repeatibility/angiogram/sp'
    # alteration: 'all'  # dummy param
    preprocessing:
        resize: [512,512]
    homography_adaptation:
        # num: 0 # dummy param
        # aggregation: 'sum' # dummy param
        # filter_counts: 0 # dummy param
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.5
model:
    name: 'superpoint' #superpoint
    using_bn: true
    pretrained_model: './export/sp_7.pth'
    grid_size: 8
    backbone:
        backbone_type: 'VGG'
        vgg:
            channels: [64,64,64,64,128,128,128,128]
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head
        feat_in_dim: 128
        feat_out_dim: 256
    learning_rate: 0.001
    nms: 4
    topk: 1000
    det_thresh: 0.015 # 0.001
    #batch_size: 50
    #eval_batch_size: 50

